"""initial schema

Revision ID: 5c9d62057922
Revises:
Create Date: 2026-05-06 22:18:31.993678

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5c9d62057922'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('phase_relevance', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('chunk_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_source_type'), 'knowledge_chunks', ['source_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_queries_this_month', sa.Integer(), nullable=False),
    sa.Column('ai_queries_reset_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('grows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grow_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('tent_width_cm', sa.Integer(), nullable=True),
    sa.Column('tent_depth_cm', sa.Integer(), nullable=True),
    sa.Column('tent_height_cm', sa.Integer(), nullable=True),
    sa.Column('lighting_watts', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grows_user_id'), 'grows', ['user_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('grow_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('messages', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grow_id'], ['grows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('pots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grow_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('volume_liters', sa.Float(), nullable=False),
    sa.Column('substrate', sa.String(length=100), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grow_id'], ['grows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pots_grow_id'), 'pots', ['grow_id'], unique=False)
    op.create_table('plants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pot_id', sa.UUID(), nullable=False),
    sa.Column('strain_name', sa.String(length=100), nullable=False),
    sa.Column('strain_type', sa.String(length=20), nullable=False),
    sa.Column('genetics', sa.String(length=20), nullable=True),
    sa.Column('seed_type', sa.String(length=20), nullable=False),
    sa.Column('germination_date', sa.Date(), nullable=True),
    sa.Column('current_phase', sa.String(length=20), nullable=False),
    sa.Column('flip_date', sa.Date(), nullable=True),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('expected_harvest_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pot_id'], ['pots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pot_id')
    )
    op.create_table('sensor_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grow_id', sa.UUID(), nullable=False),
    sa.Column('pot_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('esp32_mac', sa.String(length=20), nullable=False),
    sa.Column('firmware_version', sa.String(length=20), nullable=True),
    sa.Column('sensors_config', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grow_id'], ['grows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pot_id'], ['pots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('esp32_mac')
    )
    op.create_index(op.f('ix_sensor_devices_grow_id'), 'sensor_devices', ['grow_id'], unique=False)
    op.create_table('grow_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ppm', sa.Float(), nullable=True),
    sa.Column('ph_in', sa.Float(), nullable=True),
    sa.Column('ph_out', sa.Float(), nullable=True),
    sa.Column('water_volume_ml', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_keys', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grow_events_event_date'), 'grow_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_grow_events_event_type'), 'grow_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_grow_events_plant_id'), 'grow_events', ['plant_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temp_air', sa.Float(), nullable=True),
    sa.Column('humidity_air', sa.Float(), nullable=True),
    sa.Column('co2_ppm', sa.Integer(), nullable=True),
    sa.Column('soil_moisture_pct', sa.Float(), nullable=True),
    sa.Column('ph_solution', sa.Float(), nullable=True),
    sa.Column('ec_ms_cm', sa.Float(), nullable=True),
    sa.Column('vpd_kpa', sa.Float(), nullable=True),
    sa.Column('lux', sa.Integer(), nullable=True),
    sa.Column('temp_root', sa.Float(), nullable=True),
    sa.Column('light_leak', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['sensor_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_device_id'), 'sensor_readings', ['device_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_recorded_at'), 'sensor_readings', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_readings_recorded_at'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_device_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_grow_events_plant_id'), table_name='grow_events')
    op.drop_index(op.f('ix_grow_events_event_type'), table_name='grow_events')
    op.drop_index(op.f('ix_grow_events_event_date'), table_name='grow_events')
    op.drop_table('grow_events')
    op.drop_index(op.f('ix_sensor_devices_grow_id'), table_name='sensor_devices')
    op.drop_table('sensor_devices')
    op.drop_table('plants')
    op.drop_index(op.f('ix_pots_grow_id'), table_name='pots')
    op.drop_table('pots')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_grows_user_id'), table_name='grows')
    op.drop_table('grows')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_knowledge_chunks_source_type'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    # ### end Alembic commands ###
